### PR TITLE
require node 16 due to adapter-core 3.x.x

### PR DESCRIPTION
**Pull request by mcm1957**
Adapter requires node 16 as adapter-core 3.x.x is known to fail at node 14 or older

### CODE REVIEW

**Comment by BenAhrdt** [comment]
@mcm1957 is Here something to do?

**Comment by mcm1957** [comment]
merging the PR unless you prefer to add the engine clause by yourself.

NO new release required, its OK (for me) that the check is avaiölable at next release

**Comment by BenAhrdt** [comment]
@mcm1957 what Check?
I cant Unterstand. I habe to Remove the 14.x Check in One of the Last Versions, Or what did. you mean?

**Comment by mcm1957** [comment]
This is a PR. You can  see the changes when selecting "changes files"

This PR adds the missing engines clause into package.json. This entry ensures that ioBroker does not install this adapter at nodejs 14 or older (or more exact it requires node 16 or newer). Thats not realted to github testing but to the fact that you updated dependency apater-core to 3.x.x.

**Simple merge the PR - thats all you must do.**
NO new release required, its OK (for me) that the check is available at next release

**Comment by BenAhrdt** [comment]
@mcm1957 ok. I Wonder, why i dont have this Check i my Other afapters… and you have merged… ok i will merge it.

**Comment by mcm1957** [comment]
> @mcm1957 ok. I Wonder, why i dont have this Check i my Other afapters… and you have merged… ok i will merge it.

janitza-gridvis: engines check is already included
lowpass-filter: https://github.com/BenAhrdt/ioBroker.lowpass-filter/pull/55 - PR is already waiting for merge

----

The stable releases of the following adapters still use an older adapter-core. The current (brand new) latest versions are missing the check. I've created PRs. So please merge them and create a new release so that the check is active when requesting a stable update.

bidirection-counter: https://github.com/BenAhrdt/ioBroker.bidirectional-counter/pull/103 - Check is missing, please merge PR and create a new release

drag-indicator: https://github.com/BenAhrdt/ioBroker.drag-indicator/pull/104 - Check is missing, please merge PR and create a new release

**Pull request merged**
